### ISSUE TITLE
Gesamtaufnahme Zeitschrift

### ISSUE THREAD

**Issue by jjspp01** [ubtue/KrimDok#131]
Habe gerade bei der Auflistung der einzelnen Aufsätze  der  Zeitschrift "British Journal of Criminology" (ppn 015150712) festgestellt, dass die Aufsätze nur ab 2014 (wahrscheinlich nur die der Druckausgabe) angezeigt werden, wir haben aber schon Aufsätze von 2017 (alle elektronische Ausgabe) erfasst. Habe in sobek geprüft. Gruß P.Präg

**Comment by mtrojan-ub** [comment]
Nach der gestrigen Umstellung auf TueFind haben wir einen Fehler behoben der dazu geführt hat dass bestimmte Datensätze verloren gingen.

Können Sie bitte nochmal prüfen ob jetzt alle Datensätze vorhanden sind?

Für die von Ihnen genannte PPN werden jetzt jedenfalls auch ältere Datensätze angezeigt
Beispiel: https://sobek.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A015150712&type=AllFields&page=53

![grafik](https://user-images.githubusercontent.com/26873381/36028108-0c3dedba-0d9e-11e8-9af0-5858094c43b3.png)

**Comment by jjspp01** [comment]
Ja, es funktioniert wieder.
