### ISSUE TITLE
neues Vufind: bei "weiteren Suchoptionen, alphabetisch browsen" funktioniert nicht mehr!

### ISSUE THREAD

**Issue by jjspp01** [ubtue/KrimDok#132]

**Comment by mtrojan-ub** [comment]
Nur bei "Nach Thema", richtig?
Mittlerweile sollte es wieder funktionieren.

![grafik](https://user-images.githubusercontent.com/26873381/36027864-3fb36a40-0d9d-11e8-9ffb-815c5b4acc5e.png)

**Comment by jjspp01** [comment]
Ja, funktioniert wieder!
