### ISSUE TITLE
"E-Mail", "Export" und "Drucken" bei der Suchtrefferanzeige funktionieren nicht

### ISSUE THREAD

**Issue by KStelzel** [ubtue/KrimDok#134]
![screenshot_2018-12-13 suchergebnisse - gewalt](https://user-images.githubusercontent.com/28601515/49940004-b1900280-fede-11e8-8bc2-da071456807a.png)

Die Funktionen bitte prüfen (funktioniert weder wenn nur ein Treffer ausgewählt wird, noch mit mehreren).

**Comment by mtrojan-ub** [comment]
Ich kümmere mich drum. Bitte neue Issues in Zukunft nur noch im Repository "tuefind" anlegen, danke!

**Comment by mtrojan-ub** [comment]
Die Ursache des Problems wurde behoben, bitte nochmal kurz auf sobek testen.

**Comment by KStelzel** [comment]
- Drucken funktioniert wunderbar. 
- Export soweit ich es beurteilen kann auch. Hier wäre eine Erweiterung der Bezeichnung bei RIS gut, da Citavi recht häufig genutzt wird. Ich schlage vor: RIS (z.B. Citavi) 
- Die Email-Funktion ist bei uns eigentlich (momentan noch) überflüssig und verwirrend, weil man einen Nutzeraccount braucht, den wir nicht anbieten. Kann man diese Funktion bei uns unterdrücken?

**Comment by mtrojan-ub** [comment]
Export: Werde ich anpassen, allerdings wird das dann auch auf der Englischen Webseite so stehen. Es kann nur ein gemeinsamer Wert für alle Sprachen bei diesen Labels hinterlegt werden.
E-Mail: Sehr guter Vorschlag, werde ich ändern und gleichzeitig auch an vufind-org schicken.

**Comment by mtrojan-ub** [comment]
Kann jetzt auf sobek nochmal getestet werden!

**Comment by KStelzel** [comment]
Super! Danke!
