### ISSUE TITLE
Summary wird im selben Datensatz mehrfach angezeigt

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/KrimDok#81]
https://krimdok.uni-tuebingen.de/Record/456122133

![grafik](https://cloud.githubusercontent.com/assets/26873381/24963783/db70332e-1f9f-11e7-96b9-4ef9150fb46e.png)

Das Summary in voller Länge wird 2x angezeigt

**Comment by mtrojan-ub** [comment]
Das mittlere Summary soll verschwinden und nur ganz unten im Description-Tab erhalten bleiben, dann ist es ähnlich wie im IxTheo.

**Comment by KStelzel** [comment]
Klappt und find ich schon ganz gut. Wegen mir bräuchte es keinen Textanfang nach dem Titel - das verwirrt mich und erscheint mir immer noch "doppelt". Entweder würde ich gar nichts nach dem Titel lassen und man findet entweder eine Zusammenfassung oder eben nicht. Oder ich würde nur die interne Verlinkung mit "Zusammenfassung" (bzw. "Summary") unterhalb des Titels lassen. Den zusätzlichen Begriff "Ausführliche Beschreibung" finde ich irreführend.

**Comment by mtrojan-ub** [comment]
Wir würden es aus IT-Sicht gerne gleich lassen wie im IxTheo. Potenziell wollen wir aus technischen Gründen gerne irgendwann die verschiedenen Softwareteile zusammenführen, um den Pflegeaufwand zu verringern.
Falls das OK ist bitte den Issue zumachen, ansonsten bitte genauer Definieren welchen der beiden oben genannten Lösungsansätze weiterverfolgt werden soll.

**Comment by thefass** [comment]
Die jetzige Darstellung, einen Teil des Abstracts direkt unter dem Titel anzuzeigen und das gesamte Abstract unter dem Reiter "Beschreibung" ist eine default Einstellun und sollte für alle FIDs gleich sein.
@KStelzel : bitte Issue schließen
