### ISSUE TITLE
Suche nach Neuerwerbungen auf sobek findet keine Ergebnisse

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/KrimDok#86]
- egal ob 30 oder 60 Tage, bei beidem 0 Treffer
- im Gegensatz zu krimdok.uni-tuebingen.de

**Comment by mtrojan-ub** [comment]
... lag an Problemen beim Import, Home-Variable war nicht richtig angepasst (Stichwort Umzug vufind2 => vufind). ist jetzt behoben

**Comment by KStelzel** [comment]
Bei mir nach wie vor "Keine Ergebnisse!"

**Comment by mtrojan-ub** [comment]
hmm kann ich bestätigen, aber gestern gings. 
Hab auf sobek einen Prozess gefunden der wohl schon seit 7-8 Stunden ins Nirvana lief.
Die passenden Datensätze wurden wohl nicht importiert.
Ich werde es mir am Montag erneut anschauen, nachdem der nächste Import lief.

**Comment by mtrojan-ub** [comment]
@KStelzel : Bitte nochmal testen, tut jetzt auf sobek

**Comment by KStelzel** [comment]
Ja, funktioniert. Danke!
