### ISSUE TITLE
Suche nach Neuerwerbungen ist scheinbar auf max 200 Treffer beschränkt

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/KrimDok#87]
Aktuell nur auf krimdok.uni-tuebingen.de reproduzierbar ("Neuzugänge"), bei Suche mit Parameter "seit 60 Tagen"

**Comment by mtrojan-ub** [comment]
jetzt ebenfalls auf sobek reproduzierbar, seit issue #86 behoben

**Comment by mtrojan-ub** [comment]
Das Problem scheint mit einem Fehlverhalten von VuFind selbst zusammenzuhängen. Hier ist vermutlich erst eine Korrektur seitens des VuFind-Herstellers erforderlich.

Was mir außerdem noch aufgefallen ist: Auf die Anzahl der Tage die das Frontend übergibt (z.B. 60 Tage) schlägt TueLibILS nochmal pauschal 20 Tage drauf. Es scheint mir keinen Sinn zu machen, hier muss ich noch intern rücksprache halten (meine Kollegen sind erst am Montag wieder da).

@ruschein + @jriedl : können wir das am Montag besprechen?

> Details zur VuFind-Problematik:
> - TueLibILS überschreibt die getNewItems-Funktion von NoILS. Hier ist ein Parameter "limit" enthalten, dort sollte laut Doku enthalten sein: "The size of each page of results to retrieve" also z.B. 20
> - Die aufrufende Stelle Plugin\NewItems\getBibIDsFromCatalog ruft dies jedoch auf mit $perPage * $resultPages, was bei uns 20*10=200 ist.
> - TueLibILS verwendet dann die 200 als Limit und gibt dann die 200 IDs zurück
> 
> Das ist schon vom Design herkomplett falsch. Es sollte als Limit 20 abgefragt werden. Die Funktion sollte dann 20 IDs zurück liefern + die Anzahl die es insgesamt an IDs gibt. Das können wir aber erst dann vernünftig anpassen, wenn es in VuFind behoben wird.

**Comment by mtrojan-ub** [comment]
kann nun auf sobek ausprobiert werden, Suche nach 60 Tagen liefert aktuell 104 Treffer.

(limit liegt aktuell bei ca. 1000 im Vergleich zu ca. 200, das Limit ganz abzuschaffen wäre technisch um ein vielfaches aufwendiger, da dann auch viele Teile von VuFind umgeschrieben werden müssen).

**Comment by KStelzel** [comment]
Ja, klappt. Bei mir sind es derzeit 83 Treffer bei 60 Tagen. Aber ich kann nicht nach nur 30 Tagen suchen, das funktioniert irgendwie nicht.

**Comment by mtrojan-ub** [comment]
habs grade nochmal ausprobiert (auf krimdok/ub15)

Seit 30 Tagen: 83 Treffer
Seit 60 Tagen: 192 Treffer

bitte nochmal versuchen, falls es dann immer noch Probleme gibt bitte genauer beschreiben (oder kurz anrufen)

**Comment by KStelzel** [comment]
Ahja, stimmt. Funktioniert.
