### ISSUE TITLE
Verknüpfung vom übergeordneten Werk zu untergeordneten Werken fehlt

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/KrimDok#88]
In der Detailansicht eines untergeordneten Werkes kann man über "in" zum übergeordneten Werk springen. Beispiel 346904048 => 069458472

![grafik](https://cloud.githubusercontent.com/assets/26873381/25903102/c74f96f2-359b-11e7-90f0-abecdabdcf95.png)

Allerdings fehlt im übergeordneten Werk die Möglichkeit, nach untergeordneten Werken zu suchen.
(sollte so sein wie in IxTheo).

**Comment by mtrojan-ub** [comment]
vermutlich bug in krimdok_marc_pipeline, da SPR bei diesem Datensatz nicht gesetzt wird
(add_superior_and_alertable_flags)

**Comment by mtrojan-ub** [comment]
ist behoben, siehe:
https://sobek.ub.uni-tuebingen.de/Record/069458472

![grafik](https://cloud.githubusercontent.com/assets/26873381/25937125/c406ddd6-362a-11e7-8d9a-14757cb78456.png)

**Comment by KStelzel** [comment]
Bei meinem Test hat es heute nicht funktioniert, weder bei Büchern noch bei Zeitschriften.
![grafik](https://cloud.githubusercontent.com/assets/28601515/26000585/cd667c24-3729-11e7-8efb-cab15fc3dcda.png)

**Comment by mtrojan-ub** [comment]
@KStelzel : Bitte nochmal testen

**Comment by KStelzel** [comment]
funktioniert
