### ISSUE TITLE
Verfügbarkeitsanzeige bei Neuerwerbungen noch nicht optimal

### ISSUE THREAD

**Issue by ConstanzeWeber** [ubtue/KrimDok#91]
Bei Neuerwerbungen wird im Feld Verfügbarkeit "In Tübingen vorhanden. (IFK: bestellt 06/2016)" angegeben. Die Benutzer gehen dann davon aus, dass das Buch vorhanden ist und lediglich im Juni 2016 bestellt wurde. Das Buch ist allerdings lediglich bestellt und noch nicht vorhanden. Im SWB ist deshalb der Status "e (= Erwerbungsdaten)" im Lokalsatz gesetzt. Momentan kommt es deshalb zu ständigen Nachfragen (mehrmals wöchentlich).

![grafik](https://cloud.githubusercontent.com/assets/28625388/25948600/84712ed6-3654-11e7-956e-006a3f4d351e.png)

**Comment by KStelzel** [comment]
noch nicht behoben: Der Text lautet im Feld Verfügbarkeit immer noch "In Tübingen vorhanden. IFK: bestellt xy/xy". Das verwirrt die Nutzer, weil sie denken, dass das Buch schon vorhanden wäre...
![grafik](https://cloud.githubusercontent.com/assets/28601515/26356339/0f906718-3fcc-11e7-893a-e7466d85df4a.png)

**Comment by KStelzel** [comment]
Hat sich noch nichts geändert. Evtl. wäre ein "Im Erwerbungsprozess - IFK: bestellt: xy/xy" sinnvoll. Ginge das?

**Comment by ruschein** [comment]
Jetzt haben wir zumindest kein "In Tübingen vorhanden" mehr.

**Comment by mtrojan-ub** [comment]
Kann dieser Issue geschlossen werden?

**Comment by KStelzel** [comment]
Ganz optimal ist es ja noch nicht (s. den Kommentar oben), aber für den Moment ist es okay. Mal kucken, ob es viele Bibliotheksbenutzerfragen gibt.

**Comment by thefass** [comment]
@KStelzel : gibt es schon Erfahrungen?

**Comment by KStelzel** [comment]
Ist jetzt besser :)

**Comment by ruschein** [comment]
@KStelzel Ist ja nett, aber können wir das Issue jetzt zumachen oder was muss noch getan werden?
