### ISSUE TITLE
"Similar Items"-Tab ausblenden

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/KrimDok#95]
(gemeldet von obrandt)

https://sobek.ub.uni-tuebingen.de/Record/346904048#similar

![grafik](https://cloud.githubusercontent.com/assets/26873381/26240609/df8e5c5c-3c81-11e7-9f71-d4bcb3b8cd4c.png)

Per default sieht man die Image-Vorschau, obwohl wir nie Images gespeichert sind. Umstellen, so dass direkt der Text angezeigt wird (dies war angeblich früher so)

**Comment by mtrojan-ub** [comment]
Kleines Missverständnis: Eine zusätzliche Text-Anzeige der similar items gibts ja bereits auf der linken Seite

![grafik](https://cloud.githubusercontent.com/assets/26873381/26408375/eb0d51c6-409d-11e7-88ec-9710312679ab.png)

Daher soll der Similar Items Tab komplett deaktiviert werden

**Comment by mtrojan-ub** [comment]
done, siehe sobek

**Comment by KStelzel** [comment]
Bei mir erscheint es noch.

**Comment by mtrojan-ub** [comment]
stimmt!

jetzt bitte auf Sobek nochmal testen

**Comment by KStelzel** [comment]
Immernoch so wie zuvor...

**Comment by mtrojan-ub** [comment]
hmm, bei mir ists nun weg, siehe Screenshot.

Bitte mal mit STRG+F5 die Seite aktualisieren, falls es dann immer noch da ist, bitte Screenshot mit URL posten
![grafik](https://user-images.githubusercontent.com/26873381/28720284-fe50af0c-73ac-11e7-870d-63a6f540e3c1.png)

**Comment by KStelzel** [comment]
Bei mir ist es noch da...
![grafik](https://user-images.githubusercontent.com/28601515/28720742-5d0be5e2-73ae-11e7-8e7b-eee90d5a8b41.png)

auch bei der englischsprachigen Version
![grafik](https://user-images.githubusercontent.com/28601515/28720780-789ae9fc-73ae-11e7-9f70-94acce44eb86.png)

**Comment by KStelzel** [comment]
Ahh, es ist weg...
![grafik](https://user-images.githubusercontent.com/28601515/28721180-ba909e3c-73af-11e7-9b7c-31d8a9d40bd2.png)
