### ISSUE TITLE
keine Treffer bei Schlagwortsuche

### ISSUE THREAD

**Issue by KStelzel** [ubtue/KrimDok#96]
Die Schlagwortsuche scheint nicht zu funktionieren: Sowohl bei "Fußball" (auch bei "Fussball") als auch in der erweiterten Suche mit "Fußball" und "Gewalt" wurden mit der Einstellung "Schlagwort" bei dem bzw. beiden Suchschlitz(en) kein Treffer gefunden. Im alten Krimdok finden sich jedoch 73 respektive 33 Treffer.

**Comment by mtrojan-ub** [comment]
Dazu haben wir nun einen fix erstellt und auf sobek eingespielt. Dieser wird sich erst nach dem nächsten Import auswirken. Wir warten bis nach dem nächsten Regelimport und prüfen dann Anfang nächster Woche ob es auf sobek passt.

**Comment by mtrojan-ub** [comment]
Sucht man jetzt auf sobek mittels Schlagwortsuche nach "Fußball", werden 37 Datensätze gefunden.

@KStelzel : bitte auf sobek ausprobieren. Falls es fehlende PPNs gibt bitte diese im Ticket melden, falls alles passt bitte Issue schließen.

**Comment by KStelzel** [comment]
Puh, also auf die 37 Treffer auf sobek komme ich auch. Im alten Krimdok gibt es bei genormten SWs 65 Treffer und bei lokalen SWs 73. Irgendwas fehlt also noch immer. Falls es Not tut, kann ich die fehlenden ppns diese Woche raussuchen - heute komme ich nicht dazu.

Ich sehe gerade, dass auf sobek anscheinend nur Monographien gefunden werden, keine Zeitschriftenartikel. Vermutlich kommt daher die Differenz.

**Comment by mtrojan-ub** [comment]
Beispiel-PPN 483074977 gefunden.
Problem sind mehrere "a"-Unterfelder in LOK 689

![grafik](https://cloud.githubusercontent.com/assets/26873381/26545449/ee1f936c-4465-11e7-8e92-b9d99d5ec91c.png)

**Comment by mtrojan-ub** [comment]
So, auf Sobek ergibt die Schlagwortsuche nach "Fußball" nun 101 Treffer, davon 55 Artikel und 46 Bücher.

@KStelzel : Bitte nochmals prüfen ob nun immer noch etwas fehlt.

**Comment by KStelzel** [comment]
Scheint alles zu passen. Alle Stichproben wurden gefunden und die Anzahl von Monos und Artikeln ist auf sobek größer als im alten Krimdok. 

Ich habe ehrlich gesagt keine Ahnung, wie man ein Issue schließt...

**Comment by mtrojan-ub** [comment]
unten statt "comment" einfach "close and comment" oder nur "close issue" :) ich mach ihn dann mal zu
