### ISSUE TITLE
Probleme bei der Darstellung in der Realansicht

### ISSUE THREAD

**Issue by KStelzel** [ubtue/KrimDok#97]
- Erscheinungsjahre werden nicht korrekt angezeigt
![grafik](https://cloud.githubusercontent.com/assets/28601515/26356660/0a3bdb5c-3fcd-11e7-8fc5-c595896d6d1a.png)

- Sprachmix dt.-engl.
![grafik](https://cloud.githubusercontent.com/assets/28601515/26356676/11bfc438-3fcd-11e7-8f5a-8b3d358094ef.png)

**Comment by mtrojan-ub** [comment]
Zu Teil 1: Es handelt sich nicht um einen Softwarefehler, Details siehe #94 . Die Datensätze wurden zur Korrektur an Frau Präg gemeldet

**Comment by mtrojan-ub** [comment]
Teil 2 (Sprachmix) ist auf sobek bereits behoben. vgl:
https://krimdok.uni-tuebingen.de/Record/330251465
https://sobek.ub.uni-tuebingen.de/Record/330251465

**Comment by KStelzel** [comment]
Alles top!
